<?php
/*---------------------------------------------------+
| HoloCMS - Website and Content Management System
+----------------------------------------------------+
| Copyright &copy; 2008 Meth0d
+----------------------------------------------------+
| HoloCMS is provided "as is" and comes without
| warrenty of any kind. 
+---------------------------------------------------*/

// Disclaimer / Terms of Service
$locale['terms_of_service_title'] = "Conditions d'utilisation";
$locale['terms_of_service'] = "Bienvenue sur le site Internet d'un habbo r&eacute;tro.

Nous vous remercions de lire attentivement l'ensemble des dispositions ci-dessous qui r&eacute;gissent l'utilisation du site (ci-apr&egrave;s d&eacute;sign&eacute;es les "Conditions d'Utilisation").

Si vous avez moins de 18 ans, vous devez demander &agrave; vos parents ou tuteurs de vous expliquer tous les termes ou expressions utilis&eacute;s ci-dessous que vous ne comprenez pas et valider avec eux votre d&eacute;cision d'accepter l'ensemble des Conditions d'Utilisation.

1. Utilisation du Site Habbo Hotel
1.1 Vous &ecirc;tes autoris&eacute; par les propri&eacute;taires de Habbo Hotel, &agrave; savoir la soci&eacute;t&eacute; Sulake France, identifi&eacute;e au RCS Nanterre sous le num&eacute;ro 478 259 211, (ci-apr&egrave;s &eacute;galement d&eacute;sign&eacute;e "Sulake France" ou "nous"), et sa soci&eacute;t&eacute; m&egrave;re ou ses filiales (ci-apr&egrave;s conjointement d&eacute;sign&eacute;es le "Groupe Sulake" &agrave; acc&eacute;der et utiliser le site "Habbo Hotel" accessible par le lien www.habbo.fr, ses extensions et tout autre site qui pourrait le remplacer (ci-apr&egrave;s d&eacute;sign&eacute; le/notre "Site") &agrave; condition de respecter l'ensemble des Conditions d'Utilisation et la Charte de protection des donn&eacute;es personnelles. Nous pouvons modifier les Conditions d'Utilisation, &agrave; tout moment, afin de les adapter &agrave; l'&eacute;volution du Site. Vous serez inform&eacute; de ces modifications sur la page d'accueil du Site.
1.2 Sauf indication contraire, les Conditions d'Utilisation s'appliqueront cumulativement &agrave; toutes conditions particuli&egrave;res (ci-apr&egrave;s d&eacute;sign&eacute;es les "Conditions Particuli&egrave;res") applicables &agrave; l'utilisation de certains produits ou services propos&eacute;s par Sulake France ou par un tiers et accessibles &agrave; travers le Site. Ces Conditions Particuli&egrave;res pourront &ecirc;tre &eacute;dict&eacute;es ponctuellement en relation avec de tels produits ou services. En cas de contradiction entre les Conditions d'Utilisation et les Conditions Particuli&egrave;res, ces derni&egrave;res pr&eacute;vaudront dans la limite de l'&eacute;tendue de la contradiction des termes.
1.3 Pour utiliser les fonctionnalit&eacute;s propos&eacute;es par le Site (ces fonctionnalit&eacute;s sont ci-apr&egrave;s d&eacute;sign&eacute;es le "Service"), vous devez vous enregistrer en qualit&eacute; d'utilisateur autoris&eacute;. Pour permettre votre enregistrement, vous devez nous fournir les informations qui vous seront demand&eacute;es de mani&egrave;re sinc&egrave;re, compl&egrave;te et exacte et les maintenir &agrave; jour r&eacute;guli&egrave;rement. Vous devrez ainsi nous informer de toute modification &eacute;ventuelle de ces informations par email. En cas de communication d'informations erron&eacute;es, nous nous r&eacute;servons le droit de proc&eacute;der &agrave; la suppression de votre Compte apr&egrave;s mise en demeure de rectifier ces Informations adress&eacute;e par email non suivie d'effets dans un d&eacute;lai de quarante-huit (48) heures.
1.4 Vous &ecirc;tes responsable de la conservation du caract&egrave;re confidentiel et utilisation correcte de votre nom d'utilisateur et de votre mot de passe. Vous en assumez la garde et les risques de perte. Pour cette raison, vous devez prendre toutes les mesures n&eacute;cessaires pour assurer leur confidentialit&eacute;, leur s&eacute;curit&eacute;, et leur correcte utilisation, ainsi que pour &eacute;viter qu'ils ne soient r&eacute;v&eacute;l&eacute;s &agrave; des tiers non autoris&eacute;s. Vous &ecirc;tes seul responsable de l'utilisation par toute autre personne, de vos nom d'utilisateur et mot de passe, et notamment de toutes les op&eacute;rations qui ont &eacute;t&eacute; effectu&eacute;es par l'interm&eacute;diaire du compte que vous avez cr&eacute;&eacute; pour utiliser le Site. Vous devez nous informer imm&eacute;diatement de toute utilisation non autoris&eacute;e de votre compte ou de votre mot de passe, ainsi que de toute situation dont vous avez connaissance et qui pourrait conduire &agrave; une telle utilisation.
1.5 En cas de perte ou d'oubli de votre nom d'utilisateur ou de votre mot de passe, vous devez nous en informer et suivre les r&egrave;gles de contr&ocirc;le de s&eacute;curit&eacute; que nous pouvons &ecirc;tre amen&eacute;s &agrave; fixer. Nous pouvons suspendre vos nom d'utilisateur et mot de passe lorsque nous estimons que les r&egrave;gles de s&eacute;curit&eacute; de tout ou partie du Site n'ont pas &eacute;t&eacute; ou risquent de ne pas &ecirc;tre respect&eacute;es. Nous pouvons vous demander, de mani&egrave;re discr&eacute;tionnaire, de changer le nom d'utilisateur et/ou le mot de passe que vous utilisez afin de vous connecter au Site.
1.6 Vous vous engagez &agrave; ne pas utiliser un nom d'utilisateur ou mot de passe appartenant &agrave; un autre utilisateur, ind&eacute;pendamment de l'autorisation ou non de ce dernier.
Vous vous engagez &agrave; ne pas choisir de nom d'utilisateur portant atteinte aux droits des tiers et plus particuli&egrave;rement au droit au nom, au droit des marques ou plus g&eacute;n&eacute;ralement contraire &agrave; l'ordre public.

1.7 Nous nous r&eacute;servons le droit d'approuver ou de rejeter tout nom d'utilisateur ou mot de passe que vous aurez choisis. Nous nous r&eacute;servons &eacute;galement tous les droits, titres et int&eacute;r&ecirc;ts concernant vos nom d'utilisateur et mot de passe.
1.8 Sous r&eacute;serve des dispositions de notre Charte de protection des donn&eacute;es personnelles, nous nous r&eacute;servons le droit de transf&eacute;rer les comptes d'utilisateurs &agrave; toute soci&eacute;t&eacute; du Groupe Sulake.
1.9 L'utilisation du Site ne comprend pas la fourniture d'un ordinateur ni de tout autre mat&eacute;riel, &eacute;quipement ou service. Pour utiliser le Site, vous devez disposer de vos propres moyens de t&eacute;l&eacute;communications et d'acc&egrave;s &agrave; Internet appropri&eacute;s. Nous ne pourrons en aucun cas &ecirc;tre tenus d'assumer les &eacute;ventuels frais li&eacute;s &agrave; l'utilisation de ces moyens, tels que les frais de connexion factur&eacute;s par un op&eacute;rateur de t&eacute;l&eacute;communications ou par votre fournisseur d'acc&egrave;s &agrave; Internet.
1.10 La propri&eacute;t&eacute; de l'ensemble des contenus du Site, incluant sans limitation tout texte, donn&eacute;e, son, images, visuels, graphiques, photos, agencement du site, logiciel, et tout autre contenu du Site (ci-apr&egrave;s le "Contenu"), ainsi que la s&eacute;lection, l'organisation, la fonctionnalit&eacute;, l'ex&eacute;cution et l'arrangement du Contenu ou d'une partie du Contenu est, sauf indication contraire, exclusivement d&eacute;tenue par Sulake France, sa soci&eacute;t&eacute; m&egrave;re ou ses filiales. La marque, le nom commercial, les logos, les dessins et autres signes distinctifs ou caract&egrave;res de Sulake France ou du Groupe Sulake, incluant sans caract&egrave;re limitatif, Habbo et Habbo Hotel, sont prot&eacute;g&eacute;s au titre du droit de la propri&eacute;t&eacute; intellectuelle et ne sont susceptibles d'aucune utilisation sans l'autorisation pr&eacute;alable &eacute;crite de Sulake France ou du Groupe Sulake. Des avertissements ou restrictions suppl&eacute;mentaires, apparaissant ponctuellement au sein de certains &eacute;l&eacute;ments du Contenu, sont susceptibles de s'ajouter aux pr&eacute;sentes dispositions.
1.11 Les Logiciels pour lesquels une licence d'utilisation vous est conc&eacute;d&eacute;e (sans aucun droit de sous-licence) ne pourront &ecirc;tre utilis&eacute;s que dans le cadre du Contenu du Site. Vous ne pouvez vous enregistrer comme utilisateur qu'en tant que personne physique. Le Site est exclusivement r&eacute;serv&eacute; &agrave; une utilisation personnelle et non commerciale. Vous acceptez d'utiliser le Site conform&eacute;ment &agrave; la r&eacute;glementation applicable et &agrave; toutes r&egrave;gles et Code de conduite &eacute;dict&eacute;s par Sulake France pour l'utilisation du Site. Toute utilisation du Site ou du Contenu &agrave; d'autres fins est strictement interdite et est susceptible (i) de nous contraindre &agrave; utiliser notre droit de r&eacute;siliation et de fermeture de votre compte conform&eacute;ment aux pr&eacute;sentes Conditions d'Utilisation et/ou (ii) d'engager votre responsabilit&eacute; civile ou p&eacute;nale.
1.12 Vous ne devez pas modifier, copier, distribuer, transmettre, diffuser, afficher, reproduire, publier, conc&eacute;der une licence, cr&eacute;er des oeuvres d&eacute;riv&eacute;es, cr&eacute;er des liens hypertextes, reproduire, transf&eacute;rer ou c&eacute;der l'une quelconque des informations, du Contenu et des services accessibles &agrave; partir du Site. L'ensemble des droits de propri&eacute;t&eacute; intellectuelle de Sulake France, ou du Groupe Sulake, ou des droits de propri&eacute;t&eacute; intellectuelle des fournisseurs et partenaires de Sulake sont prot&eacute;g&eacute;s &agrave; ce titre. Si vous souhaitez davantage d'information sur ce qui est autoris&eacute; d'utiliser ou de reproduire, sur la possibilit&eacute; de cr&eacute;er un lien hypertexte vers le site ou vers le Contenu, nous vous prions de nous en avertir et de solliciter une autorisation par email.
1.13 Vous ne devez pas tenter d'acc&eacute;der &agrave; nos syst&egrave;mes d'informations ou &agrave; nos bases de donn&eacute;es sans autorisation.
1.14 Vous vous engagez &agrave; utiliser Habbo Hotel uniquement &agrave; travers le Site, et non pas &agrave; travers un site miroir ou tout autre moyen. Vous vous engagez &eacute;galement &agrave; ne pas cr&eacute;er ou fournir d'autres moyens permettant une utilisation de Habbo Hotel par d'autres personnes, par exemple des &eacute;mulateurs de serveurs. Vous n'&ecirc;tes pas autoris&eacute; &agrave; effectuer des op&eacute;rations d'ing&eacute;nierie inverse, &agrave; d&eacute;compiler ou &agrave; d&eacute;sassembler les Logiciels, y compris tous protocoles de communications utilis&eacute;s par les Logiciels ou le Site.

2. Utilisation du Service
2.1 Le Service comprend un service de messagerie instantan&eacute;e, ainsi que des forums de discussion sur lesquels les utilisateurs peuvent envoyer les messages qu'ils souhaitent faire publier. Vous vous engagez &agrave; utiliser ces services exclusivement aux fins de poster, envoyer et recevoir des messages et contenus appropri&eacute;s, conformes aux exigences du site et des pr&eacute;sentes conditions d'utilisation. Vous &ecirc;tes seul responsable des informations, r&eacute;sultat de sondage, photographies, messages ou autres contenus que vous envoyez ou introduisez sur le site (« le Contenu des utilisateurs ») et des cons&eacute;quences r&eacute;sultant de l'introduction d'un tel contenu sur le Site. Lorsque vous utilisez le service, vous vous engagez notamment &agrave; ne pas :
2.1.1 Utiliser le Service &agrave; des fins d'enqu&ecirc;te, de concours, de ventes pyramidales ou autres op&eacute;rations similaires, ou d'envoi de courriers en cha&icirc;ne, de courriels, de spams ou de toute publicit&eacute; ou &eacute;l&eacute;ment promotionnel non sollicit&eacute;s, que cela soit &agrave; des fins commerciales ou non ;
2.1.2 Abuser, harceler, menacer, tenir des propos diffamatoires, obsc&egrave;nes, racistes ou portant atteinte aux droits des autres (notamment les droits relatifs au respect de la vie priv&eacute;e et la publicit&eacute;);
2.1.3 Publier, afficher, t&eacute;l&eacute;charger, distribuer ou diffuser toute information qui sa) serait illicite ou contraire aux dispositions l&eacute;gales ou r&eacute;glementaires applicables ou qui inciterait &agrave; des activit&eacute;s de cette nature ; b) aurait un caract&egrave;re p&eacute;dophile, pornographique, explicitement sexuel, violent ou obsc&egrave;ne ; c) requerrait la communication de donn&eacute;es &agrave; caract&egrave;re personnel d'une personne &acirc;g&eacute;e de moins de quinze (15) ans ; d) aurait un caract&egrave;re raciste ou haineux ou incitant au racisme ou &agrave; la haine envers d'autres personnes ou un groupe de personnes ; f) violerait les droits de propri&eacute;t&eacute; intellectuelle de toute personne, en ce compris les droits d'auteur ou les droits de propri&eacute;t&eacute; industrielle d) serait diffamatoires ; h) constituerait une affirmation fausse &agrave; propos d'une personne ou ses biens ou son activit&eacute; professionnelle faite par malveillance et susceptible de causer un pr&eacute;judice financier &agrave; cette personne ; i) aurait un caract&egrave;re fallacieux ou trompeur ; j) constituerait une violation d'une obligation de confidentialit&eacute; ou une atteinte au droit &agrave; la vie priv&eacute;e d'une personne ; k) pourrait nous conduire &agrave; la violation ou nous impliquer dans la violation d'une disposition l&eacute;gale ou r&eacute;glementaire, d'un code ou d'un instrument qui r&eacute;git notre comportement ; l) pourrait engager notre responsabilit&eacute; &agrave; l'&eacute;gard de toute personne ; m) autrement porterait atteinte aux droits de toute personne.
2.1.4 T&eacute;l&eacute;charger vers le Site des fichiers contenant des logiciels ou tout autre &eacute;l&eacute;ment prot&eacute;g&eacute; par des droits de propri&eacute;t&eacute; intellectuelle ou des droits relatifs &agrave; la vie priv&eacute;e ou la publicit&eacute;, &agrave; moins que vous ne disposiez des droits y aff&eacute;rents ou des autorisations n&eacute;cessaires &agrave; leur exploitation ;
2.1.5 T&eacute;l&eacute;charger vers le Site des fichiers comprenant des virus, des chevaux de Troie, des vers, des bombes logiques, des fichiers alt&eacute;r&eacute;s ou tout autre logiciel ou code nuisible aux ordinateurs ou &agrave; la propri&eacute;t&eacute; d'autrui ;
2.1.6 Faire de la publicit&eacute; ou inciter des personnes &agrave; acheter ou vendre des biens et services dans un but commercial ;
2.1.7 T&eacute;l&eacute;charger tout fichier envoy&eacute; par un autre utilisateur d&egrave;s lors que vous savez, ou que vous pouvez raisonnablement douter, que ce fichier ne peut &ecirc;tre librement mis &agrave; la disposition d'autrui de cette mani&egrave;re ;
2.1.8 Falsifier ou effacer toute indication identifiant un auteur, toute mention l&eacute;gale, tout titre de propri&eacute;t&eacute; ou marquage d&eacute;signant l'origine d'un logiciel ou de tout autre &eacute;l&eacute;ment contenu dans un fichier t&eacute;l&eacute;charg&eacute; vers le Site ;
2.1.9 Restreindre ou emp&ecirc;cher l'utilisation du Service par tout autre utilisateur ;
2.1.10 Enfreindre les r&egrave;gles de bonne conduite, ou toute r&egrave;gle &eacute;dict&eacute;e sur le Site pour tout service ou &eacute;v&egrave;nement particulier;
2.1.11 R&eacute;colter/collecter des donn&eacute;es personnelles d'autres personnes, y compris des adresses email ou des pseudonymes, dans le but d'envoyer des spams ou emails ind&eacute;sirables, ou de transmettre des informations personnelles concernant d'autres individus ;
2.1.12 Violer toute loi ou r&eacute;glementation en vigueur, ou tous droits de propri&eacute;t&eacute; intellectuelle appartenant &agrave; un tiers ;
2.1.13 Tenter d'induire en erreur d'autres utilisateurs en cr&eacute;ant une fausse identit&eacute; ou en usurpant le nom d'autrui ;
2.1.14 Manipuler des en-t&ecirc;tes ou tout autre identifiants de mani&egrave;re &agrave; dissimuler l'origine de tout &eacute;l&eacute;ment transmis via le Service ;
2.1.15 Utiliser, t&eacute;l&eacute;charger &agrave; partir du Site ou autrement reproduire ou fournir &agrave; quiconque (&agrave; titre gratuit ou on&eacute;reux) tout annuaire des utilisateurs du Site ou toute autre information relative &agrave; des utilisateurs ou &agrave; l'utilisation du Site.
2.1.16 Refuser de suivre les instructions de tout repr&eacute;sentant de Sulake France ou du Groupe Sulake
2.1.17 Si vous constatez la pr&eacute;sence sur le Site de Contenus manifestement illicites tels que ceux dont la publication est interdite par l'article 2.1.3, vous pouvez nous le signaler en nous envoyant un email.
2.2 Sous r&eacute;serve des dispositions l&eacute;gales imp&eacute;ratives applicables, nous ne nous engageons pas &agrave; surveiller le contenu, les messages et autres informations qui sont rendus disponibles sur le Site par ses utilisateurs. Nous nous r&eacute;servons n&eacute;anmoins le droit, sans que cela ne puisse constituer une obligation, de revoir certains &eacute;l&eacute;ments mis en ligne notamment sur les pages d'accueil ou le forum de discussion, et de retirer, &agrave; notre seule discr&eacute;tion, tout &eacute;l&eacute;ment disponible &agrave; travers le Service.
2.3 Nous nous r&eacute;servons le droit discr&eacute;tionnaire de divulguer &agrave; tout moment toute information pour nous permettre de respecter la r&eacute;glementation en vigueur ou la demande d'une autorit&eacute; comp&eacute;tente, et de modifier, refuser de publier ou retirer toute information ou autre &eacute;l&eacute;ment disponible sur le Site.
2.4 Nous n'avalisons pas les contenus, messages et informations mis en ligne par les utilisateurs et pour cette raison, nous ne pouvons &ecirc;tre tenus responsables des cons&eacute;quences de votre utilisation du Service, et en particulier de votre participation ou de celle de tout autre utilisateur sur les pages d'accueil, aux forums de discussion, messagerie instantan&eacute;e ou tout autre service interactif.
2.5 Les &eacute;l&eacute;ments t&eacute;l&eacute;charg&eacute;s vers les pages d'accueil, les forums de discussion, messagerie instantan&eacute;e ou tout autre service peuvent &ecirc;tre limit&eacute;s quant &agrave; l'&eacute;tendue de leur utilisation, leur reproduction et/ou leur diffusion. Dans le cas o&ugrave; vous t&eacute;l&eacute;chargez ces &eacute;l&eacute;ments, vous devez respecter toutes les limitations applicables.
2.6 Vous conservez l'ensemble des droits, titres et int&eacute;r&ecirc;ts que vous d&eacute;tenez sur les contenus que vous publiez sur le Site. Toutefois, en publiant des contenus sur le Site, vous nous accordez &agrave; nous ainsi qu'aux soci&eacute;t&eacute;s qui nous sont li&eacute;es, &agrave; nos sous-traitants et &agrave; nos partenaires une licence &agrave; titre non exclusif, valable pendant toute la dur&eacute;e de votre utilisation du Site (ainsi que le droit de sous-licencier tout ou partie des droits suivants) afin d'utiliser, d'&eacute;diter, de modifier, de reproduire, de publier et de distribuer le contenu que vous avez publi&eacute; sur le Site en lien avec celui-ci et &agrave; des fins commerciales raisonnables (en ce compris la publicit&eacute; et le marketing). Vous accordez &eacute;galement aux autres utilisateurs du Site une licence non exclusive d'acc&eacute;der aux contenus que vous publiez sur le Site, et de reproduire et d'exposer les contenus que vous publiez sur le Site via le Site. Vous nous garantissez &eacute;galement contre les troubles de fait et de droit caus&eacute;s par des tiers qui se pr&eacute;tendraient &ecirc;tre les v&eacute;ritables propri&eacute;taires des droits sur les contenus que vous publiez.
2.7 Nous nous r&eacute;servons le droit d'effacer les comptes passifs depuis plus de six mois qui (i) n'ont &eacute;t&eacute; utilis&eacute;s qu'une seule fois pour leur ouverture, (ii) ne contiennent pas de Cr&eacute;dits Habbo et (iii) ne contiennent pas d'amis, ces crit&egrave;res &eacute;tant cumulatifs.

3. Licences de logiciels
3.1 Nous mettons &agrave; votre disposition certains logiciels (les "Logiciels") que vous &ecirc;tes autoris&eacute;s &agrave; t&eacute;l&eacute;charger sur le site afin d'am&eacute;liorer votre utilisation de ce dernier. Le t&eacute;l&eacute;chargement ou l'obtention par tout autre moyen de tout &eacute;l&eacute;ment accessible dans le cadre de l'utilisation du site est faite &agrave; vos risques et p&eacute;rils, et, &agrave; cet &eacute;gard, vous &ecirc;tes exclusivement responsable de tous dommages caus&eacute;s &agrave; votre syst&egrave;me informatique et de toute perte de donn&eacute;es que vous pourriez subir. Les logiciels contiennent des informations confidentielles et prot&eacute;g&eacute;es par le droit de la propri&eacute;t&eacute; intellectuelle. L'utilisation des logiciels doit &ecirc;tre effectu&eacute;e conform&eacute;ment aux contrats de licence d'utilisation accompagnant ou int&eacute;gr&eacute;s dans les logiciels (le "Contrat de licence"). Ces contrats identifient &eacute;galement le propri&eacute;taire des logiciels (le "Propri&eacute;taire").
3.2 Vous devez respecter les droits des Propri&eacute;taires des logiciels et ne pouvez notamment pas effectuer de copie, reproduction, transfert, modification ou cr&eacute;ation d'oeuvres d&eacute;riv&eacute;es des logiciels, par exemple sur un autre serveur ou tout autre lieu en vue de reproductions ult&eacute;rieures, de redistribution, de ventes, de pr&ecirc;ts, de location quelconque, sauf si cela est express&eacute;ment permis par le Contrat de licence applicable.
3.3 Nous n'offrons aucune garantie relative aux Logiciels. Les seules garanties dont vous disposez concernant les Logiciels sont celles offertes par le Propri&eacute;taire dans le cadre du Contrat de licence applicable.

4. Services payants
4.1 Nous offrons des services am&eacute;lior&eacute;s (les "Services Am&eacute;lior&eacute;s") sur le Site moyennant le paiement d'un prix. Ces Services Am&eacute;lior&eacute;s consistent notamment en des services de t&eacute;l&eacute;chargement d'ic&ocirc;nes et de sonneries de t&eacute;l&eacute;phone portable, la participation &agrave; certains jeux et activit&eacute;s, la souscription &agrave; des lettres d'information, l'adoption d'«animaux virtuels» ou la fourniture de «meubles virtuels» afin de garnir une pi&egrave;ce de r&eacute;ception au sein de Habbo Hotel.
4.2 Tous les produits disponibles sur le Catalogue de Habbo Hotel sont conserv&eacute;s sur nos serveurs, et l'acc&egrave;s &agrave; ces produits est soumis aux pr&eacute;sentes Conditions d'Utilisation. Ces produits ne peuvent en aucun cas &ecirc;tre t&eacute;l&eacute;charg&eacute;s vers votre ordinateur.
4.3 Nous pouvons, &agrave; notre convenance, retirer ou ajouter des nouveaux Services Am&eacute;lior&eacute;s. Ces Services Am&eacute;lior&eacute;s seront toujours payants.
4.4 Nous d&eacute;terminons les modalit&eacute;s de paiement des Services Am&eacute;lior&eacute;s et ces modalit&eacute;s peuvent varier dans le temps. Nous pouvons vous offrir des Cr&eacute;dits Habbo qui peuvent &ecirc;tre utilis&eacute;s pour l'obtention de Services Am&eacute;lior&eacute;s. Les Cr&eacute;dits Habbo sont d&eacute;duits de votre compte au fur et &agrave; mesure que vous effectuez des achats. En aucun cas les Cr&eacute;dits Habbo ne sont convertibles en euros.
4.5 Sous r&eacute;serve de dispositions contraires &eacute;dict&eacute;es par la loi ou en rapport avec des offres de services particuli&egrave;res, aucun paiement ou frais ne sera rembours&eacute;.
4.6 D&egrave;s lors que vous nous commandez des Services et notamment des Services Am&eacute;lior&eacute;s par l'interm&eacute;diaire du Site, et sous r&eacute;serves des dispositions l&eacute;gales applicables, vous ne pouvez, &agrave; compter de la mise &agrave; disposition de ces services, mettre fin au contrat existant entre vous et nous qu'en respectant les dispositions des pr&eacute;sentes Conditions d'Utilisation ou des Conditions Particuli&egrave;res pouvant accompagner l'
offre de certains Services.
4.7 Si vous &ecirc;tes &acirc;g&eacute; de moins de dix-huit (18) ans, vous devez obtenir l'autorisation de la personne qui r&egrave;gle la facture avant d'accepter de vous engagez &agrave; payer des frais.

5. Exclusion de garanties
5.1 D&eacute;faut d'exactitude du Contenu de L'ensemble du Contenu propos&eacute; par le Site (y compris le Contenu des Utilisateurs) vous est fourni &agrave; titre personnel seulement. Sulake France ou les autres soci&eacute;t&eacute;s du Groupe Sulake ne sauraient &ecirc;tres tenues responsables du Contenu du Site, notamment des pages d'accueil, des forums de discussions ou des messageries instantan&eacute;es. Le Contenu (&agrave; l'exclusion du contenu des utilisateurs) et informations mis &agrave; votre disposition sur le Site sont exacts lorsqu'ils sont mis en ligne sur le Site par Sulake France. Toutefois, nous ne fournissons aucune garantie quant &agrave; l'exactitude &agrave; tout moment, le caract&egrave;re complet ou &agrave; jour de ces informations. Nous ne pouvons pas &ecirc;tre tenus responsables des cons&eacute;quences d'une d&eacute;pendance de ce contenu qui vous serait pr&eacute;judiciable.
5.2 D&eacute;faut de fonctionnement du Site. Nous vous fournissons le Site en l'&eacute;tat. Nous ne garantissons pas que le Site ou les Contenus seront disponibles, de mani&egrave;re permanente et exempte de toute erreur. Nous n'offrons aucune garantie relative au fonctionnement du Site ou son Contenu ni aux informations qu'il contient. En particulier, nous n'offrons aucune garantie quant &agrave; la qualit&eacute;, l'exactitude, l'efficacit&eacute;, l'exhaustivit&eacute; et les performances du Site, ni quant &agrave; l'absence sur le Site de toute erreur, virus ou autre code pouvant conduire &agrave; la contamination ou la destruction de syst&egrave;mes d'information, ainsi que le d&eacute;faut de tout dysfonctionnement ou interruption du Service. En cons&eacute;quence, ni la responsabilit&eacute; de Sulake France, ni celle des autres soci&eacute;t&eacute;s du Groupe Sulake, ne peuvent &ecirc;tre engag&eacute;es concernant les &eacute;l&eacute;ments susmentionn&eacute;s.

5.3 S&eacute;curit&eacute; : A l'exception des dispositions express de notre CHARTE DE PROTECTION DES DONN&Eacute;ES PERSONNELLES, Sulake France n'offre aucune garantie quant &agrave; la s&eacute;curit&eacute; des informations que vous seriez amen&eacute; &agrave; divulguer ni quant aux activit&eacute;s que vous seriez amen&eacute; &agrave; exercer au cours de l'utilisation du Site.
5.4 SOUS R&Eacute;SERVE DES DISPOSITIONS L&Eacute;GALES, NOUS EXCLUONS TOUTE GARANTIE EXPRES OU IMPLICITE S'AGISSANT DE VOTRE UTILISATION DU SITE. NOUS N'APPORTONS AUCUNE GARANTIE QUANT AUX CONTENUS PR&Eacute;SENTS SUR LE SITE OU LES CONTENUS PR&Eacute;SENTS SUR D'AUTRES SITES INTERNET AUXQUELS RENVOIENT DES LIENS PR&Eacute;SENTS SUR LE SITE. Vous reconnaissez express&eacute;ment assumer l'ensemble des risques li&eacute;s &agrave; l'utilisation du Site et de son Contenu, produits et services (y compris notamment des pages d'accueil, forums de discussion et messageries instantan&eacute;es), des Logiciels et autres activit&eacute;s propos&eacute;es sur le Site, et &ecirc;tre seul responsable des cons&eacute;quences d'une telle utilisation.
5.5 L'utilisation du Site est assortie de garanties qui, aux termes de la l&eacute;gislation protectrice des consommateurs, ne peuvent &ecirc;tre exclues et selon lesquelles, notamment, le Site devra &ecirc;tre mis &agrave; disposition avec soin et &ecirc;tre conforme &agrave; la destination qui lui est attribu&eacute;e.

6. Exclusion et limitation de responsabilit&eacute;
6.1 Dans la mesure autoris&eacute;e par la loi, nous ne pourrons &ecirc;tre responsable et excluons express&eacute;ment toute responsabilit&eacute; pour pertes ou dommages que vous auriez subi en raison a) des Contenus pr&eacute;sents sur le Site ou sur d'autres sites Internet auxquels renvoient des liens pr&eacute;sents sur le site, notamment pour toute erreur, omission ou inexactitude concernant de tels Contenus ; b) de biens ou de services qui vous auraient &eacute;t&eacute; fournis par un tiers via le Site ; c) de tout Contenu publi&eacute; sur le Site sous vos noms et mot de passe ; d) de la suppression ou de l'&eacute;chec de la conservation ou de la transmission de tout Contenu sur le Site ; e) d'une atteinte aux biens subie dans le cadre de votre utilisation du Site ; f) d'un acc&egrave;s non autoris&eacute; &agrave; vos donn&eacute;es &agrave; caract&egrave;re personnel conserv&eacute;es dans nos bases de donn&eacute;es ; g) des failles et virus qu'un tiers pourrait avoir transmis &agrave; votre ordinateur dans le cadre de votre utilisation du Site ; ou h) de toute interruption du fonctionnement du Site.
6.2 NOUS EXCLUONS EXPRESS&Eacute;MENT TOUTE RESPONSABILIT&Eacute; A VOTRE &Eacute;GARD AU TITRE DE, OU CONCERNANT, LA PERTE INDIRECTE OU CONS&Eacute;CUTIVE, NOTAMMENT LA PRIVATION DE JOUISSANCE, LE MANQUE A GAGNER, LA PERTE D'UNE CHANCE, LA PERTE DE DONN&Eacute;ES, LA PERTE DE PRODUCTION, LA PERTE D'OPPORTUNIT&Eacute;S OU L'ARR&Ecirc;T D'EXPLOITATION SUBI DU FAIT DE VOTRE UTILISATION DU SITE.
6.3 SOUS R&Eacute;SERVE DES STIPULATIONS QUI PR&Eacute;C&Eacute;DENT, SI NOTRE RESPONSABILIT&Eacute; DEVAIT &Ecirc;TRE ENGAG&Eacute;E DANS LE CADRE DE VOTRE UTILISATION DU SITE, LE MONTANT DE L'INDEMNISATION A LAQUELLE VOUS POUVEZ PR&Eacute;TENDRE EST LIMITE AU MONTANT DES SOMMES QUE VOUS AVEZ PAY&Eacute;ES DURANT LES TROIS DERNIERS MOIS PR&Eacute;C&Eacute;DANT IMM&Eacute;DIATEMENT LE FAIT G&Eacute;N&Eacute;RATEUR DE L'ACTION, LE CAS &Eacute;CH&Eacute;ANT.
6.4 Vous reconnaissez que les exclusions et limitations de responsabilit&eacute; pr&eacute;vues aux Articles 6.1, 6.2 et 6.3 s'appliquent quelque soit la nature du dommage, perte, co&ucirc;t, d&eacute;penses ou action et quelque soit le fondement de cette action et la nature de la pr&eacute;tendue responsabilit&eacute; recherch&eacute;e.

7. Indemnisation
Vous acceptez de nous indemniser ainsi que nos ayants droits, de toutes les pertes, d&eacute;penses, dommages et co&ucirc;ts, dans la mesure du raisonnable, responsabilit&eacute;, r&eacute;clamation et frais engag&eacute;s (y compris, sur la base d'une r&eacute;paration int&eacute;grale, de tout frais juridique ou engag&eacute;s pour notre d&eacute;fense ou tout r&egrave;glement amiable) pouvant r&eacute;sulter a) du non-respect des pr&eacute;sentes Conditions d'Utilisation, b) de l'utilisation du Site avec vos nom d'utilisateur et mot de passe ou c) d'une atteinte de votre part aux droits de tiers. Les dispositions de ce paragraphe sont destin&eacute;es &agrave; prot&eacute;ger Sulake France et ses g&eacute;rants, responsables, employ&eacute;s, agents, actionnaires, conc&eacute;dants de licence et fournisseurs. Chacune de ces personnes ou entit&eacute;s pourra, en son propre nom, faire valoir ces dispositions directement &agrave; votre encontre.

8. Garantie
Vous nous garantissez que : a) vous avez la capacit&eacute; et les pouvoirs requis pour conclure ce Contrat et ex&eacute;cuter les obligations qui en r&eacute;sultent pour vous ; b) vous d&eacute;tenez tous les droits aff&eacute;rents aux Contenus que vous publiez sur le Site ou que le propri&eacute;taire de ces Contenus vous a accord&eacute; tous les droits requis pour les publier sur le Site ; c) les Contenus que vous publiez sur le Site sont conformes &agrave; l'article 2 des pr&eacute;sentes (Limites applicables aux Contenus) ; d) vous assumerez le paiement de tout honoraire, redevance ou autre somme du &agrave; des tiers (en ce compris les soci&eacute;t&eacute;s de gestion collective des droits d'auteurs) au titre des Contenus que vous publiez sur le Site ; et e) que vous avez la capacit&eacute; et les pouvoirs requis pour effectuer toute acquisition sur le Site.

9. Liens vers les sites Internet exploit&eacute;s par des tiers
9.1 Vous reconnaissez et acceptez que certains liens sur le site renvoient vers des ressources situ&eacute;es sur des serveurs exploit&eacute;s par des tiers sur lesquels nous n'exer&ccedil;ons pas de contr&ocirc;le et dont les activit&eacute;s ne sont pas contr&ocirc;l&eacute;es par Sulake France. en cons&eacute;quence, nous excluons toute responsabilit&eacute; concernant la disponibilit&eacute; et le contenu des ressources et sites accessibles par ces serveurs. Vous &ecirc;tes seul responsable de l'&eacute;valuation des biens et services offerts par lesdits tiers par le biais du site. dans ce cadre, nous ne sommes pas parties et ne supportons aucune responsabilit&eacute; dans le cadre de la transaction que vous pouvez conclure avec ces tiers, ni m&ecirc;me du contenu des informations que ces derniers pourraient fournir dans le cadre de leurs offres.
9.2 En utilisant les liens vers les sites de tiers qui sont accessibles sur le site, vous pouvez recevoir des "cookies" et vos donn&eacute;es personnelles sont susceptibles d'&ecirc;tre collect&eacute;es. nous excluons toute responsabilit&eacute; &agrave; cet &eacute;gard dans la mesure o&ugrave; nous n'exer&ccedil;ons aucun contr&ocirc;le sur ces sites et ces actions.
9.3 S'agissant des annonces publicitaires et tout autre &eacute;l&eacute;ment relatif &agrave; la publicit&eacute; figurant sur le site et soumis par des tiers, lesdits tiers, en tant qu'annonceurs, sont seuls responsables de la conformit&eacute; de leurs annonces et &eacute;l&eacute;ments avec la r&eacute;glementation applicable, et nous excluons toute responsabilit&eacute; &agrave; cet &eacute;gard.

10. R&egrave;gles g&eacute;n&eacute;rales de conduite et de stockage
10.1 Nous nous r&eacute;servons le droit d'&eacute;tablir des r&egrave;gles de conduite et de poser des limites quant &agrave; l'utilisation du service. Nous pouvons, par exemple, fixer :
(a) un nombre maximum de jours pendant lesquels les messages ou tout autre contenu t&eacute;l&eacute;charg&eacute; vers le site seront conserv&eacute;s dans le cadre du service ;
(b) un nombre ou un volume maximum des messages qui peuvent &ecirc;tre envoy&eacute;s ou re&ccedil;us par un compte ouvert sur le service ;
(c) une capacit&eacute; de m&eacute;moire maximum qui sera allou&eacute;e par nos serveurs pour votre compte ;
(d) un nombre maximum de fois o&ugrave; vous pouvez acc&eacute;der au service, ainsi qu'une dur&eacute;e maximale de chaque acc&egrave;s pendant une p&eacute;riode donn&eacute;e.

11. Protection des donn&eacute;es personnelles
Les informations personnelles que vous nous fournissez sont trait&eacute;es en stricte conformit&eacute; &agrave; notre Charte de protection des donn&eacute;es personnelles qui fournit notamment des d&eacute;tails sur vos droits concernant vos donn&eacute;es personnelles et qui fait partie int&eacute;grante des pr&eacute;sentes conditions d'utilisation. Les termes "donn&eacute;es personnelles" sont d&eacute;finis &agrave; cette Charte. Nous vous invitons &agrave; la lire attentivement avant de nous communiquer vos donn&eacute;es personnelles. Si vous n'adh&eacute;rez pas aux termes de cette Charte, nous vous prions de ne pas nous communiquer de telles donn&eacute;es &agrave; caract&egrave;re personnel. Nous attirons votre attention sur le fait que cette charte ne s'applique pas aux sites Internet op&eacute;r&eacute;s par des tiers.

12. R&eacute;siliation et suspension
12.1 Vous pouvez r&eacute;silier ce Contrat &agrave; tout moment et pour n'importe quelle raison (par exemple parce que nous n'avons pas respect&eacute; les termes de ce Contrat) sans p&eacute;nalit&eacute;s en nous envoyant un email. Si vous avez pay&eacute; afin d'acc&eacute;der &agrave; des fonctionnalit&eacute;s du Site soumises &agrave; des p&eacute;riodes minimum d'abonnement par application des Conditions particuli&egrave;res qui leur sont applicables, vous aurez acc&egrave;s au Site jusqu'&agrave; l'expiration du terme, sous r&eacute;serve que nous ne mettions pas en oeuvre notre propre droit &agrave; r&eacute;siliation conform&eacute;ment &agrave; l'article 12.2 des pr&eacute;sentes. En tout &eacute;tat de cause, nous ne proc&eacute;derons &agrave; aucun remboursement de toute ou partie des sommes que nous vous aurons d&eacute;j&agrave; factur&eacute;es et ce Contrat restera pleinement applicable jusqu'&agrave; son terme.
12.2 Nous pouvons mettre fin &agrave; ce Contrat &agrave; tout moment, avec ou sans notification pr&eacute;alable : a) si vous ne respectez pas ou si nous avons des motifs raisonnables de croire que vous n'avez pas respect&eacute; les termes de ce Contrat, apr&egrave;s notification pr&eacute;alable de mettre fin &agrave; la violation du Contrat ; ou b) si votre compte est inactif depuis plus de six mois et que vous n'avez pas acc&egrave;s &agrave; des fonctionnalit&eacute;s payantes. Nous pourrons &eacute;galement mettre fin &agrave; ce Contrat &agrave; tout moment et pour n'importe quelle raison apr&egrave;s vous en avoir pr&eacute;alablement inform&eacute; un mois auparavant par un email envoy&eacute; &agrave; l'adresse que vous nous avez communiqu&eacute;e. En cas de r&eacute;siliation au titre de l'article 12.2 a) vous ne pourrez pr&eacute;tendre au remboursement des sommes que vous nous avez vers&eacute;es.
12.3 Nous pouvons suspendre l'acc&egrave;s &agrave; votre compte si vous ne respectez pas ou si nous avons des motifs raisonnables de croire que vous n'avez pas respect&eacute; les termes de ce Contrat. Dans ce cas, vous ne pourrez pr&eacute;tendre au remboursement des sommes que vous nous avez vers&eacute;es

13. Cons&eacute;quence de la r&eacute;siliation
Si vous mettez fin, si nous mettons fin &agrave; ce Contrat ou si nous suspendons l'acc&egrave;s &agrave; votre compte respectivement en vertu des articles 12.1, 12.2 ou 12.3, nous pourrons supprimer votre profil (incluant les informations fournies pour l'inscription) et tout Contenu que vous aurez publi&eacute; sur le Site. Pour cette raison, nous vous recommandons de conserver une copie de tout Contenu (en particulier des articles de blog, des images, des fichiers vid&eacute;os et audio) que vous aurez publi&eacute; sur le Site. Nous nous r&eacute;servons le droit de conserver votre profil et tout Contenu que vous aurez publi&eacute; sur le Site, sur nos serveurs pendant une p&eacute;riode raisonnable apr&egrave;s la r&eacute;siliation de ce Contrat.

14. Modification du site
14.1 Nous nous r&eacute;servons le droit discr&eacute;tionnaire de modifier, de suspendre ou de mettre fin &agrave; l'exploitation du Site ou de supprimer une fonctionnalit&eacute; &agrave; tout moment et pour n'importe quelle raison.
14.2 La modification du Site par application de l'article 14.1 pourra &ecirc;tre effectu&eacute;e sans notification pr&eacute;alable lorsqu'elle aura un impact positif ou neutre pour vous.
14.3 Si la modification du Site par application de l'article 14.1 est susceptible d'avoir un impact mat&eacute;riel n&eacute;gatif sur vous, nous vous adresserons, au pr&eacute;alable, comme il se doit, une notification de cette modification par email &agrave; l'adresse que vous nous avez communiqu&eacute;e et vous pourrez exercer votre droit de r&eacute;silier ce Contrat conform&eacute;ment &agrave; l'article 12.1 des pr&eacute;sentes.
Un exemple de modification du Site qui pourrait avoir un impact mat&eacute;riel n&eacute;gatif sur vous pourrait &ecirc;tre la suppression d'une fonctionnalit&eacute; clef du Site mise en avant, sans offrir une fonctionnalit&eacute; alternative comparable.
14.4 Si la modification du Site mise en oeuvre suppose que vous changiez de logiciel, d'&eacute;quipement ou de connexion Internet pour continuer &agrave; l'utilisez, les frais aff&eacute;rents &agrave; de tels changements seront &agrave; votre seule charge.

15. Modification des conditions d'utilisation
15.1 Nous nous r&eacute;servons le droit discr&eacute;tionnaire de modifier le pr&eacute;sent Contrat, y compris en augmentant les frais d'acc&egrave;s aux fonctionnalit&eacute;s du Site &agrave; tout moment. Votre utilisation du Site apr&egrave;s la mise en oeuvre de telles modifications sera r&eacute;put&eacute;e valoir acceptation de ce Contrat modifi&eacute; de votre part.
15.2 La modification du Contrat par application de l'article 15.1 pourra &ecirc;tre effectu&eacute;e sans notification pr&eacute;alable lorsqu'elle aura un impact positif ou neutre pour vous.
15.3 Si la modification du Contrat par application de l'article 15.1 est susceptible d'avoir un impact mat&eacute;riel n&eacute;gatif sur vous, nous vous informerons de ces modifications, au pr&eacute;alable, comme il se doit, par un message mis en ligne sur la page d'accueil du pr&eacute;sent Site, et vous pourrez exercer votre droit de r&eacute;silier ce Contrat conform&eacute;ment &agrave; l'article 12.1 des pr&eacute;sentes.
15.4 Nous vous invitons &agrave; consulter r&eacute;guli&egrave;rement la version mise &agrave; jour de ce Contrat ICI

16. Concours et lots &agrave; gagner
P&eacute;riodiquement, nous ou nos partenaires organiserons des concours, jeux, tirages au sort gratuits et promotions sur le Site. Ceux-ci feront l'objet de Conditions Particuli&egrave;res que nous communiquerons lors de ces jeux concours.

17. S&eacute;curit&eacute; sur Internet
Si vous &ecirc;tes &acirc;g&eacute; de moins de dix-huit (18) ans et que vous avez l'intention d'utiliser le Site, vous devez lire et respecter les r&egrave;gles de s&eacute;curit&eacute; Internet disponibles sur le lien http://www.mineurs.fr/index.htm.

18. Protection des droits d'auteur
Si vous estimez que la pr&eacute;sence d'un Contenu porte atteinte &agrave; vos droits d'auteurs, nous vous prions de bien vouloir nous contacter par email afin de nous le signaler.

19. Dispositions g&eacute;n&eacute;rales
19.1 Les pr&eacute;sentes Conditions d'Utilisation sont r&eacute;gies par la loi fran&ccedil;aise. Sous r&eacute;serve de l'application des dispositions d'ordre public, tout litige n&eacute; &agrave; l'occasion de l'utilisation du Site ou des Conditions d'Utilisation rel&egrave;vera de la comp&eacute;tence exclusive des tribunaux fran&ccedil;ais.
19.2 Le fait pour nous de ne pas exercer, ou de tarder &agrave; exercer l'un quelconque des droits que nous d&eacute;tenons au titre des pr&eacute;sentes Conditions d'Utilisation ou de la loi, ne peut constituer ni ne peut &ecirc;tre interpr&eacute;t&eacute; comme une renonciation aux droits dont il s'agit. Si l'un des articles des pr&eacute;sentes Conditions d'Utilisation est consid&eacute;r&eacute; comme caduc ou nul par toute juridiction comp&eacute;tente, il sera r&eacute;put&eacute; non &eacute;crit mais n'entra&icirc;nera pas la nullit&eacute; ni la caducit&eacute; des autres articles des pr&eacute;sentes Conditions d'Utilisation.
19.3 La cession des droits dont vous disposez en vertu des pr&eacute;sentes est soumise &agrave; notre accord pr&eacute;alable, que vous pouvez solliciter en nous envoyant email.
19.4 Vous reconnaissez et acceptez que nous pouvons, &agrave; tout moment, c&eacute;der et transf&eacute;rer &agrave; un tiers les droits et responsabilit&eacute;s qui r&eacute;sultent des pr&eacute;sentes; ce tiers pourra d&egrave;s lors assumer les responsabilit&eacute;s et obligations stipul&eacute;es aux pr&eacute;sentes et nous vous adresserons une notification dans une telle hypoth&egrave;se.
19.5 Les titres des articles des pr&eacute;sentes Condition d'Utilisation n'ont qu'une valeur indicative.
19.6 Les pr&eacute;sentes Condition d'Utilisation constituent l'int&eacute;gralit&eacute; de l'accord entre vous et nous concernant votre utilisation du Site.
19.7 Sauf dispositions contraires, les montants des prix sont indiqu&eacute;s et payables en euros.
AVANT TOUTE UTILISATION DU SITE, VOUS RECONNAISSEZ AVOIR PRIS CONNAISSANCE ET ACCEPTE LES PR&Eacute;SENTES CONDITIONS D'UTILISATION AINSI QUE NOTRE CHARTE DE PROTECTION DES DONN&Eacute;ES PERSONNELLES.

Ceci est la copie des conditions d'utilisation d'Habbo.fr
Nous vous rapellons aussi que les habbos r&eacute;tros sont ill&eacute;gaux.";

// Privacy Policy
$locale['privacy_policy_title'] = "Informations pratiques";
$locale['privacy_policy'] = "Sur <b>".$sitename."</b>, votre vie priv&eacute;e n'est pas remise en cause sur ce jeu. Toutes vos donn&eacute;es personnelles sont s&eacute;curis&eacute;e dans notre base de donn&eacute;es, et vos mots de passe sont encrypt&eacute;s.
De plus, nous n'utiliserons aucun de vos comptes &agrave; des fins personnelles.

Ce CMS &agrave; &eacute;t&eacute; cr&eacute;e par Meth0d, et modifi&eacute; en version francaise par Bubble et Knock.
NakedCMS - NakedGroup

Partenaires:  Aucun partenaire";

?>